### ISSUE TITLE
launching problems

### ISSUE THREAD

**Issue by ghost** [gl91306/lunar#7]
launching takes a long time, i lost my patient and tried to close the window, but it doesnt close

**Comment by gl91306** [comment]
go to lunar settings and put ur ram wayy down, that might be the problem. What model of Pi do you have?

**Comment by ghost** [comment]
Pi 4 4gb version 1.1

**Comment by ghost** [comment]
but why turn ram down

**Comment by gl91306** [comment]
launching may take a long time cause lunar has a lot of mods to load. Turning ram down is important, because with too much ram allocated ur pi will slow it down and cause the long loading time. Also its kinda hard to talk on github, so heres the link to the pi-ware discord, just ping me in the #testing channel and ill reply

**Comment by gl91306** [comment]
Closing as discussion was moved to discord
